server:
  port: 8080

spring:
  profiles.active: dev  
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging.config: classpath:log4j2-dev.xml 

chatgpt:
  api:
    key: 
    endpoint: https://api.openai.com/v1/completions  
